# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('answered_by', models.IntegerField()),
                ('team_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('questionNumber', models.IntegerField(default=0)),
            ],
        ),
    ]
