# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
