# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0003_question_proceed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='proceed',
            new_name='proceed_status',
        ),
    ]
