# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0005_question_no_of_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answered_by',
            field=models.CharField(max_length=100),
        ),
    ]
