# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0007_remove_question_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='marks',
            new_name='score',
        ),
    ]
