# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0008_auto_20160310_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 9, 22, 46, 43, 760572, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
