# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0009_question_time_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.CharField(max_length=100)),
            ],
        ),
    ]
