# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0011_auto_20160310_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='proceed_status',
            new_name='time_elapsed',
        ),
    ]
