# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0012_auto_20160310_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNumber', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
